name: CI

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 18
          cache: gradle

      - name: assemble
        run: |
          ./gradlew assemble assembleAndroidTest

      - name: unit tests
        run: |
          ./gradlew test

      - name: testLab
        env:
          GCP_SERVICE_KEY: ${{ secrets.GCP_SERVICE_KEY }}
        run: |
          echo "$GCP_SERVICE_KEY" > service-key.json
          gcloud auth activate-service-account --key-file service-key.json
          gcloud config set project androidtestsdemo-1
          gcloud firebase test android run --type instrumentation --app ./app/build/outputs/apk/debug/app-debug.apk --test ./app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk --device model=Pixel2,version=30 --use-orchestrator
